/**
 * Erlaubte Werte der mobile.de-Aufzaehlungsfelder.
 *
 * NICHT VON HAND AENDERN — erzeugt von mobile-werte-holen.mjs.
 * Stand: 2026-08-30
 * Quelle: https://services.mobile.de/refdata/...
 *
 * Je Eintrag [Wert, deutsche Bezeichnung]. Gesendet wird der erste;
 * der zweite steht daneben, damit beim Lesen klar ist, worum es geht.
 *
 * Warum als Datei: Diese Woerter sehen vorhersehbar aus. Man schreibt
 * "CLOTH", richtig waere "FABRIC". Auffallen wuerde es erst, wenn
 * mobile.de das fertige Inserat eines echten Kunden ablehnt.
 *
 * 24 Felder, 376 Werte.
 */

export const MOBILE_WERTE: Record<string, [string, string][]> = {
  gearbox: [
    ['MANUAL_GEAR', 'Schaltgetriebe'],
    ['SEMIAUTOMATIC_GEAR', 'Halbautomatik'],
    ['AUTOMATIC_GEAR', 'Automatik'],
  ],
  fuel: [
    ['PETROL', 'Benzin'],
    ['DIESEL', 'Diesel'],
    ['LPG', 'Autogas (LPG)'],
    ['CNG', 'Erdgas (CNG)'],
    ['ELECTRICITY', 'Elektro'],
    ['HYBRID', 'Hybrid (Benzin/Elektro)'],
    ['HYDROGENIUM', 'Wasserstoff'],
    ['ETHANOL', 'Ethanol (FFV, E85 etc.)'],
    ['HYBRID_DIESEL', 'Hybrid (Diesel/Elektro)'],
    ['OTHER', 'Andere'],
  ],
  exteriorColor: [
    ['BLACK', 'Schwarz'],
    ['GREY', 'Grau'],
    ['BEIGE', 'Beige'],
    ['BROWN', 'Braun'],
    ['RED', 'Rot'],
    ['GREEN', 'Grün'],
    ['BLUE', 'Blau'],
    ['PURPLE', 'Violett'],
    ['GOLD', 'Gold'],
    ['WHITE', 'Weiß'],
    ['ORANGE', 'Orange'],
    ['SILVER', 'Silber'],
    ['YELLOW', 'Gelb'],
  ],
  interiorColor: [
    ['BLACK', 'Schwarz'],
    ['GREY', 'Grau'],
    ['BEIGE', 'Beige'],
    ['BROWN', 'Braun'],
    ['RED', 'Rot'],
    ['BLUE', 'Blau'],
    ['OTHER_INTERIOR_COLOR', 'Andere'],
  ],
  interiorType: [
    ['LEATHER', 'Vollleder'],
    ['PARTIAL_LEATHER', 'Teilleder'],
    ['FABRIC', 'Stoff'],
    ['VELOUR', 'Velours'],
    ['ALCANTARA', 'Alcantara'],
    ['IMITATION_LEATHER', 'Kunstleder'],
    ['OTHER_INTERIOR_TYPE', 'Andere'],
  ],
  condition: [
    ['USED', 'Gebrauchtfahrzeug'],
    ['NEW', 'Neufahrzeug'],
  ],
  emissionClass: [
    ['EURO1', 'Euro1'],
    ['EURO2', 'Euro2'],
    ['EURO3', 'Euro3'],
    ['EURO4', 'Euro4'],
    ['EURO5', 'Euro5'],
    ['EURO6', 'Euro6'],
    ['EURO6C', 'Euro6c'],
    ['EURO6D_TEMP', 'Euro6d-TEMP'],
    ['EURO6D', 'Euro6d'],
    ['EURO6E', 'Euro 6e'],
    ['EURO7', 'Euro 7'],
  ],
  emissionSticker: [
    ['EMISSIONSSTICKER_GREEN', '4 (Grün)'],
    ['EMISSIONSSTICKER_YELLOW', '3 (Gelb)'],
    ['EMISSIONSSTICKER_RED', '2 (Rot)'],
    ['EMISSIONSSTICKER_NONE', '1 (Keine)'],
  ],
  doors: [
    ['TWO_OR_THREE', '2/3'],
    ['FOUR_OR_FIVE', '4/5'],
    ['SIX_OR_SEVEN', '6/7'],
  ],
  airbag: [
    ['DRIVER_AIRBAG', 'Fahrer-Airbag'],
    ['FRONT_AIRBAGS', 'Front-Airbags'],
    ['FRONT_AND_SIDE_AIRBAGS', 'Front- und Seiten-Airbags'],
    ['FRONT_AND_SIDE_AND_MORE_AIRBAGS', 'Front-, Seiten- und weitere Airbags'],
  ],
  climatisation: [
    ['NO_CLIMATISATION', 'Keine Klimaanlage oder -automatik'],
    ['MANUAL_CLIMATISATION', 'Klimaanlage'],
    ['AUTOMATIC_CLIMATISATION', 'Klimaautomatik'],
    ['AUTOMATIC_CLIMATISATION_2_ZONES', '2-Zonen-Klimaautomatik'],
    ['AUTOMATIC_CLIMATISATION_3_ZONES', '3-Zonen-Klimaautomatik'],
    ['AUTOMATIC_CLIMATISATION_4_ZONES', '4-Zonen-Klimaautomatik'],
  ],
  parkingAssistants: [
    ['FRONT_SENSORS', 'Vorne'],
    ['REAR_SENSORS', 'Hinten'],
    ['REAR_VIEW_CAM', 'Kamera'],
    ['AUTOMATIC_PARKING', 'Selbstlenkende Systeme'],
    ['CAM_360_DEGREES', '360°-Kamera'],
  ],
  speedControl: [
    ['CRUISE_CONTROL', 'Tempomat'],
    ['ADAPTIVE_CRUISE_CONTROL', 'Abstandstempomat'],
  ],
  radio: [
    ['TUNER', 'Tuner/Radio'],
    ['DAB_RADIO', 'Radio DAB'],
  ],
  headlightType: [
    ['XENON_HEADLIGHTS', 'Xenonscheinwerfer'],
    ['BI_XENON_HEADLIGHTS', 'Bi-Xenon Scheinwerfer'],
    ['LED_HEADLIGHTS', 'LED-Scheinwerfer'],
    ['LASER_HEADLIGHTS', 'Laserlicht'],
  ],
  daytimeRunningLamps: [
    ['DAYTIME_RUNNING_LIGHTS', 'Tagfahrlicht'],
    ['LED_RUNNING_LIGHTS', 'LED-Tagfahrlicht'],
  ],
  bendingLightsType: [
    ['BENDING_LIGHTS', 'Kurvenlicht'],
    ['ADAPTIVE_BENDING_LIGHTS', 'Adaptives Kurvenlicht'],
  ],
  trailerCouplingType: [
    ['TRAILER_COUPLING_PREPARATION', 'Anhängerkupplung-Vorbereitung'],
    ['TRAILER_COUPLING_FIX', 'Anhängerkupplung fest'],
    ['TRAILER_COUPLING_SWIVELING', 'Anhängerkupplung schwenkbar'],
    ['TRAILER_COUPLING_DETACHABLE', 'Anhängerkupplung abnehmbar'],
  ],
  breakdownService: [
    ['SPARE_WHEEL', 'Reserverad'],
    ['EMERGENCY_WHEEL', 'Notrad'],
    ['REPAIR_KIT', 'Pannenkit'],
  ],
  usageType: [
    ['PRE_REGISTRATION', 'Tageszulassung'],
    ['EMPLOYEES_CAR', 'Jahreswagen'],
    ['CLASSIC', 'Oldtimer'],
    ['DEMONSTRATION', 'Vorführfahrzeug'],
  ],
  driveType: [
    ['FRONT', 'Frontantrieb'],
    ['REAR', 'Heckantrieb'],
    ['ALL_WHEEL', 'Allrad'],
  ],
  countryVersion: [
    ['AA', 'undefined'],
    ['AC', 'undefined'],
    ['AD', 'Andorra'],
    ['AE', 'Vereinigte Arabische Emirate'],
    ['AF', 'Afghanistan'],
    ['AG', 'Antigua und Barbuda'],
    ['AI', 'Anguilla'],
    ['AL', 'Albanien'],
    ['AM', 'Armenien'],
    ['AN', 'Niederländische Antillen'],
    ['AO', 'Angola'],
    ['AP', 'Asia-Pacific'],
    ['AQ', ''],
    ['AR', 'Argentinien'],
    ['AS', 'Samoainseln'],
    ['AT', 'Österreich'],
    ['AU', 'Australien'],
    ['AX', ''],
    ['AW', ''],
    ['AZ', 'Aserbaidschan'],
    ['BA', 'Bosnien und Herzegowina'],
    ['BB', 'Barbados'],
    ['BD', 'Bangladesch'],
    ['BE', 'Belgien'],
    ['BF', 'Burkina Faso'],
    ['BG', 'Bulgarien'],
    ['BH', 'Bahrain'],
    ['BI', 'Burundi'],
    ['BJ', 'Benin'],
    ['BM', 'Bermuda'],
    ['BN', 'Brunei Darussalam'],
    ['BO', 'Bolivien'],
    ['BR', 'Brasilien'],
    ['BS', 'Bahamas'],
    ['BT', 'Bhutan'],
    ['BV', ''],
    ['BW', 'Botswana'],
    ['BY', 'Weißrussland'],
    ['BZ', 'Belize'],
    ['CA', 'Kanada'],
    ['CC', 'Cocos (Keeling) Islands'],
    ['CD', 'Kongo, Demokratische Republik'],
    ['CF', 'Zentralafrikanische Republik'],
    ['CG', 'Kongo'],
    ['CH', 'Schweiz'],
    ['CI', 'Elfenbeinküste'],
    ['CK', 'Cookinseln'],
    ['CL', 'Chile'],
    ['CM', 'Kamerun'],
    ['CN', 'China'],
    ['CO', 'Kolumbien'],
    ['CR', 'Costa Rica'],
    ['CS', 'Serbien und Montenegro'],
    ['CU', 'Kuba'],
    ['CV', 'Kap Verde'],
    ['CX', 'Weihnachtsinsel'],
    ['CY', 'Zypern'],
    ['CZ', 'Tschechische Republik'],
    ['DE', 'Deutschland'],
    ['DJ', 'Djibouti'],
    ['DK', 'Dänemark'],
    ['DM', 'Dominica'],
    ['DO', 'Dominikanische Republik'],
    ['DZ', 'Algerien'],
    ['EC', 'Ecuador'],
    ['EE', 'Estland'],
    ['EG', 'Ägypten'],
    ['EH', 'Western Sahara'],
    ['ER', 'Eritrea'],
    ['ES', 'Spanien'],
    ['ET', 'Äthiopien'],
    ['EU', 'EU-Ausführung'],
    ['FI', 'Finnland'],
    ['FJ', 'Fiji'],
    ['FK', 'Falklandinseln'],
    ['FL', 'undefined'],
    ['FM', 'Föderierte Staaten von Mikronesien'],
    ['FO', 'Faröer'],
    ['FR', 'Frankreich'],
    ['GA', 'Gabun'],
    ['GB', 'Großbritannien'],
    ['GD', 'Grenada'],
    ['GE', 'Georgien'],
    ['GF', 'Guinea'],
    ['GH', 'Ghana'],
    ['GI', 'Gibraltar'],
    ['GL', 'Grönland'],
    ['GM', 'Gambia'],
    ['GN', 'Guinea'],
    ['GP', 'Guadeloupe'],
    ['GQ', 'Equatorial Guinea'],
    ['GR', 'Griechenland'],
    ['GS', ''],
    ['GT', 'Guatemala'],
    ['GU', 'Guam'],
    ['GW', 'Guinea-Bissau'],
    ['GY', 'Guyana'],
    ['HK', 'Hongkong'],
    ['HM', ''],
    ['HN', 'Honduras'],
    ['HR', 'Kroatien'],
    ['HT', 'Haiti'],
    ['HU', 'Ungarn'],
    ['ID', 'Indonesien'],
    ['IE', 'Irland'],
    ['IL', 'Israel'],
    ['IN', 'Indien'],
    ['IO', ''],
    ['IQ', 'Irak'],
    ['IR', 'Iran'],
    ['IS', 'Island'],
    ['IT', 'Italien'],
    ['JM', 'Jamaika'],
    ['JO', 'Jordanien'],
    ['JE', ''],
    ['JP', 'Japan'],
    ['KE', 'Kenia'],
    ['KG', 'Kirgisistan'],
    ['KH', 'Kambodia'],
    ['KI', 'Kiribati'],
    ['KM', 'Komoren'],
    ['KN', 'Saint Kitts and Nevis'],
    ['KP', 'Korea, Demokratische Volksrepublik'],
    ['KR', 'Südkorea'],
    ['KW', 'Kuwait'],
    ['KY', 'Cayman Islands'],
    ['KZ', 'Kasachstan'],
    ['LA', 'Laos'],
    ['LB', 'Libanon'],
    ['LC', 'St. Lucia'],
    ['LI', 'Liechtenstein'],
    ['LK', 'Sri Lanka'],
    ['LR', 'Liberia'],
    ['LS', 'Lesotho'],
    ['LT', 'Litauen'],
    ['LU', 'Luxemburg'],
    ['LV', 'Lettland'],
    ['LY', 'Libysch-Arabische Dschamahirija'],
    ['MA', 'Marokko'],
    ['MC', 'Monaco'],
    ['MD', 'Moldawien'],
    ['ME', 'Montenegro'],
    ['MG', 'Madagaskar'],
    ['MH', 'Marshallinseln'],
    ['MK', 'Mazedonien'],
    ['ML', 'Mali'],
    ['MM', 'Birma'],
    ['MN', 'Mongolei'],
    ['MO', 'Macao'],
    ['MP', ''],
    ['MQ', 'Martinique'],
    ['MR', 'Mauretanien'],
    ['MS', 'Montserrat'],
    ['MT', 'Malta'],
    ['MU', 'Mauritius'],
    ['MV', 'Malediven'],
    ['MW', 'Malawi'],
    ['MX', 'Mexiko'],
    ['MY', 'Malaysia'],
    ['MZ', 'Mosambik'],
    ['NA', 'Namibia'],
    ['NC', 'Neukaledonien'],
    ['NE', 'Niger'],
    ['NF', 'Norfolkinsel'],
    ['NG', 'Nigeria'],
    ['NI', 'Nicaragua'],
    ['NL', 'Niederlande'],
    ['NO', 'Norwegen'],
    ['NP', 'Nepal'],
    ['NR', 'Nauru'],
    ['NU', 'Niue'],
    ['NZ', 'Neuseeland'],
    ['OM', 'Oman'],
    ['PA', 'Panama'],
    ['PE', 'Peru'],
    ['PF', 'Französisch-Polynesien'],
    ['PG', 'Papua-Neuguinea'],
    ['PH', 'Philippinen'],
    ['PK', 'Pakistan'],
    ['PL', 'Polen'],
    ['PM', 'Saint-Pierre und Miquelon'],
    ['PN', ''],
    ['PR', 'Puerto Rico'],
    ['PS', 'Palästinensischen Autonomiegebiete'],
    ['PT', 'Portugal'],
    ['PW', 'Palau'],
    ['PY', 'Paraguay'],
    ['QA', 'Qatar'],
    ['QM', 'undefined'],
    ['QN', 'undefined'],
    ['QO', 'undefined'],
    ['QP', 'undefined'],
    ['RE', 'Réunion'],
    ['RO', 'Rumänien'],
    ['RS', 'Serbien'],
    ['RU', 'Russland'],
    ['RW', 'Ruanda'],
    ['SA', 'Saudi-Arabien'],
    ['SB', 'Salomoninseln'],
    ['SC', 'Seychellen'],
    ['SD', 'Sudan'],
    ['SE', 'Schweden'],
    ['SG', 'Singapur'],
    ['SH', 'Saint Helena'],
    ['SI', 'Slowenien'],
    ['SJ', ''],
    ['SK', 'Slowakische Republik'],
    ['SL', 'Sierra Leone'],
    ['SM', 'San Marino'],
    ['SN', 'Senegal'],
    ['SO', 'Somalia'],
    ['SR', 'Surinam'],
    ['ST', 'Sao Tome and Principe'],
    ['SV', 'El Salvador'],
    ['SY', 'Syrien'],
    ['SZ', 'Swasiland'],
    ['TC', 'Turks- und Caicosinseln'],
    ['TD', 'Tschad'],
    ['TF', ''],
    ['TG', 'Togo'],
    ['TH', 'Thailand'],
    ['TJ', 'Tajikistan'],
    ['TK', 'Tokelau'],
    ['TM', 'Turkmenistan'],
    ['TN', 'Tunesien'],
    ['TO', 'Tonga'],
    ['TP', 'undefined'],
    ['TR', 'Türkei'],
    ['TT', 'Trinidad und Tobago'],
    ['TV', 'Tuvalu'],
    ['TW', 'Taiwan'],
    ['TZ', 'Tansania'],
    ['UA', 'Ukraine'],
    ['UG', 'Uganda'],
    ['UM', 'undefined'],
    ['US', 'USA'],
    ['UY', 'Uruguay'],
    ['UZ', 'Usbekistan'],
    ['VA', 'Vatikanstadt'],
    ['VC', 'Saint Vincent und Grenadinen'],
    ['VE', 'Venezuela'],
    ['VG', ''],
    ['VI', ''],
    ['VN', 'Vietnam'],
    ['VU', 'Vanuatu'],
    ['WF', 'Wallis und Futuna'],
    ['WS', 'Samoa'],
    ['YE', 'Jemen'],
    ['YT', 'Mayotte'],
    ['YU', 'undefined'],
    ['ZA', 'Südafrika'],
    ['ZM', 'Sambia'],
    ['ZW', 'Simbabwe'],
    ['ZZ', 'Andere'],
  ],
  category: [
    ['Cabrio', 'Cabrio/Roadster'],
    ['EstateCar', 'Kombi'],
    ['Limousine', 'Limousine'],
    ['OffRoad', 'SUV/Geländewagen/Pickup'],
    ['SmallCar', 'Kleinwagen'],
    ['SportsCar', 'Sportwagen/Coupé'],
    ['Van', 'Van/Minibus'],
    ['OtherCar', 'Andere'],
  ],
  vehicleClass: [
    ['AgriculturalVehicle', 'Agrarfahrzeug'],
    ['Bus', 'Bus'],
    ['Car', 'Pkw'],
    ['ConstructionMachine', 'Baumaschine'],
    ['EBike', 'E-Bike'],
    ['ForkliftTruck', 'Stapler'],
    ['Motorbike', 'Motorrad'],
    ['Motorhome', 'Wohnmobil oder -wagen'],
    ['SemiTrailer', 'Auflieger'],
    ['SemiTrailerTruck', 'Sattelzugmaschine (SZM)'],
    ['Trailer', 'Anhänger'],
    ['TruckOver7500', 'Lkw über 7,5 t'],
    ['VanUpTo7500', 'Transporter oder Lkw bis 7,5 t'],
  ],
};

/** Ist der Wert fuer dieses Feld erlaubt? */
export function mobileWertGueltig(feld: string, wert: string): boolean {
  const liste = MOBILE_WERTE[feld];
  return !!liste && liste.some(([w]) => w === wert);
}
